### ISSUE TITLE
Feature Request: Authorization

### ISSUE THREAD

**Issue by timscott** [papodaca/graphql_playground-rails#43]
I would like to have the playground available in production, but only accessible to an admin user. How hard would it be to add a hook for authentication just for the GET of the page?

**Comment by papodaca** [comment]
This gem does not need to be changed to achieve what you are asking for.

[See devise](https://github.com/heartcombo/devise/wiki/How-To:-Define-resource-actions-that-require-authentication-using-routes.rb).

[Sidekiq](https://github.com/mperham/sidekiq/wiki/Monitoring#authentication) has many examples also guarding via the routes file.
