### ISSUE TITLE
Fix spelling in Github description

### ISSUE THREAD

**Issue by OzzieOrca** [papodaca/graphql_playground-rails#9]
<img width="704" alt="Screen Shot 2019-03-12 at 4 32 21 PM" src="https://user-images.githubusercontent.com/756501/54243124-7359ad80-44e4-11e9-959a-24869deedb94.png">

```diff
- An engine to provice GraphQL Playground on Rails
+ An engine to provide GraphQL Playground on Rails
```
?
or
`An engine to serve GraphQL Playground from Rails`
`An engine to host GraphQL Playground from Rails`
idk

**Comment by papodaca** [comment]
Thanks for pointing this out.
